package com.boc.model;
// Generated Nov 7, 2016 6:21:29 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * IndexIdBase generated by hbm2java
 */
@Entity
@Table(name = "INDEX_ID_BASE", schema = "WFCONFIG")
public class IndexIdBase implements java.io.Serializable {

	private int idxId;
	private BigDecimal indexRate;
	private String description;
	private Set<LoanProductIndexIdMapping> loanProductIndexIdMappings = new HashSet<LoanProductIndexIdMapping>(0);

	public IndexIdBase() {
	}

	public IndexIdBase(int idxId, BigDecimal indexRate, String description) {
		this.idxId = idxId;
		this.indexRate = indexRate;
		this.description = description;
	}

	public IndexIdBase(int idxId, BigDecimal indexRate, String description,
			Set<LoanProductIndexIdMapping> loanProductIndexIdMappings) {
		this.idxId = idxId;
		this.indexRate = indexRate;
		this.description = description;
		this.loanProductIndexIdMappings = loanProductIndexIdMappings;
	}

	@Id

	@Column(name = "IDX_ID", unique = true, nullable = false)
	public int getIdxId() {
		return this.idxId;
	}

	public void setIdxId(int idxId) {
		this.idxId = idxId;
	}

	@Column(name = "INDEX_RATE", nullable = false, precision = 6, scale = 4)
	public BigDecimal getIndexRate() {
		return this.indexRate;
	}

	public void setIndexRate(BigDecimal indexRate) {
		this.indexRate = indexRate;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indexIdBase")
	public Set<LoanProductIndexIdMapping> getLoanProductIndexIdMappings() {
		return this.loanProductIndexIdMappings;
	}

	public void setLoanProductIndexIdMappings(Set<LoanProductIndexIdMapping> loanProductIndexIdMappings) {
		this.loanProductIndexIdMappings = loanProductIndexIdMappings;
	}

}
