package com.boc.model;
// Generated Aug 1, 2016 2:20:00 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * LoanPurposes generated by hbm2java
 */
@Entity
@Table(name = "LOAN_PURPOSES", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "LOAN_PURPOSES") )
public class LoanPurposes implements java.io.Serializable {

	private int pid;
	private ProductCategoryBase productCategoryBase;
	private String loanPurposes;

	public LoanPurposes() {
	}

	public LoanPurposes(int pid, String loanPurposes) {
		this.pid = pid;
		this.loanPurposes = loanPurposes;
	}

	public LoanPurposes(int pid, ProductCategoryBase productCategoryBase, String loanPurposes) {
		this.pid = pid;
		this.productCategoryBase = productCategoryBase;
		this.loanPurposes = loanPurposes;
	}

	@Id

	@Column(name = "PID", unique = true, nullable = false)
	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_CATEGORY_ID")
	public ProductCategoryBase getProductCategoryBase() {
		return this.productCategoryBase;
	}

	public void setProductCategoryBase(ProductCategoryBase productCategoryBase) {
		this.productCategoryBase = productCategoryBase;
	}

	@Column(name = "LOAN_PURPOSES", unique = true, nullable = false, length = 100)
	public String getLoanPurposes() {
		return this.loanPurposes;
	}

	public void setLoanPurposes(String loanPurposes) {
		this.loanPurposes = loanPurposes;
	}

}
