package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PicklistvaluesMaster generated by hbm2java
 */
@Entity
@Table(name = "PICKLISTVALUES_MASTER", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = {
		"PICKLIST_NAME", "PICKLIST_CODE" }))
public class PicklistvaluesMaster implements java.io.Serializable {

	private int picklistId;
	private String picklistCode;
	private String pickValue;
	private String picklistName;
	private String picklistFilter;

	public PicklistvaluesMaster() {
	}

	public PicklistvaluesMaster(int picklistId, String picklistCode, String pickValue, String picklistName,
			String picklistFilter) {
		this.picklistId = picklistId;
		this.picklistCode = picklistCode;
		this.pickValue = pickValue;
		this.picklistName = picklistName;
		this.picklistFilter = picklistFilter;
	}

	@Id

	@Column(name = "PICKLIST_ID", unique = true, nullable = false)
	public int getPicklistId() {
		return this.picklistId;
	}

	public void setPicklistId(int picklistId) {
		this.picklistId = picklistId;
	}

	@Column(name = "PICKLIST_CODE", nullable = false, length = 50)
	public String getPicklistCode() {
		return this.picklistCode;
	}

	public void setPicklistCode(String picklistCode) {
		this.picklistCode = picklistCode;
	}

	@Column(name = "PICK_VALUE", nullable = false, length = 100)
	public String getPickValue() {
		return this.pickValue;
	}

	public void setPickValue(String pickValue) {
		this.pickValue = pickValue;
	}

	@Column(name = "PICKLIST_NAME", nullable = false, length = 50)
	public String getPicklistName() {
		return this.picklistName;
	}

	public void setPicklistName(String picklistName) {
		this.picklistName = picklistName;
	}

	@Column(name = "PICKLIST_FILTER", nullable = false, length = 20)
	public String getPicklistFilter() {
		return this.picklistFilter;
	}

	public void setPicklistFilter(String picklistFilter) {
		this.picklistFilter = picklistFilter;
	}

}
