package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PrivateEmployerBase generated by hbm2java
 */
@Entity
@Table(name = "PRIVATE_EMPLOYER_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "EMPOLYER_NAME"))
public class PrivateEmployerBase implements java.io.Serializable {

	private int eid;
	private String empolyerName;

	public PrivateEmployerBase() {
	}

	public PrivateEmployerBase(int eid, String empolyerName) {
		this.eid = eid;
		this.empolyerName = empolyerName;
	}

	@Id

	@Column(name = "EID", unique = true, nullable = false)
	public int getEid() {
		return this.eid;
	}

	public void setEid(int eid) {
		this.eid = eid;
	}

	@Column(name = "EMPOLYER_NAME", unique = true, nullable = false, length = 100)
	public String getEmpolyerName() {
		return this.empolyerName;
	}

	public void setEmpolyerName(String empolyerName) {
		this.empolyerName = empolyerName;
	}

}
