package com.boc.model;
// Generated Jun 27, 2016 5:09:31 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RequestMessageTypeBase generated by hbm2java
 */
@Entity
@Table(name = "REQUEST_MESSAGE_TYPE_BASE", schema = "WFCONFIG")
public class RequestMessageTypeBase implements java.io.Serializable {

	private int requestMessageTypeId;
	private String requestMessageName;
	private String className;
	private String requestServiceName;
	private String responseActivityName;

	public RequestMessageTypeBase() {
	}

	public RequestMessageTypeBase(int requestMessageTypeId, String requestMessageName, String responseActivityName) {
		this.requestMessageTypeId = requestMessageTypeId;
		this.requestMessageName = requestMessageName;
		this.responseActivityName = responseActivityName;
	}

	public RequestMessageTypeBase(int requestMessageTypeId, String requestMessageName, String className,
			String requestServiceName, String responseActivityName) {
		this.requestMessageTypeId = requestMessageTypeId;
		this.requestMessageName = requestMessageName;
		this.className = className;
		this.requestServiceName = requestServiceName;
		this.responseActivityName = responseActivityName;
	}

	@Id

	@Column(name = "REQUEST_MESSAGE_TYPE_ID", unique = true, nullable = false)
	public int getRequestMessageTypeId() {
		return this.requestMessageTypeId;
	}

	public void setRequestMessageTypeId(int requestMessageTypeId) {
		this.requestMessageTypeId = requestMessageTypeId;
	}

	@Column(name = "REQUEST_MESSAGE_NAME", nullable = false, length = 25)
	public String getRequestMessageName() {
		return this.requestMessageName;
	}

	public void setRequestMessageName(String requestMessageName) {
		this.requestMessageName = requestMessageName;
	}

	@Column(name = "CLASS_NAME", length = 100)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	@Column(name = "REQUEST_SERVICE_NAME", length = 100)
	public String getRequestServiceName() {
		return this.requestServiceName;
	}

	public void setRequestServiceName(String requestServiceName) {
		this.requestServiceName = requestServiceName;
	}

	@Column(name = "RESPONSE_ACTIVITY_NAME", nullable = false, length = 100)
	public String getResponseActivityName() {
		return this.responseActivityName;
	}

	public void setResponseActivityName(String responseActivityName) {
		this.responseActivityName = responseActivityName;
	}

}
