package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRoleProductCategoryMapping generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_PRODUCT_CATEGORY_MAPPING", schema = "WFCONFIG")
public class UserRoleProductCategoryMapping implements java.io.Serializable {

	private int urpcid;
	private int uid;
	private int rid;
	private int productCategoryId;

	public UserRoleProductCategoryMapping() {
	}

	public UserRoleProductCategoryMapping(int urpcid, int uid, int rid, int productCategoryId) {
		this.urpcid = urpcid;
		this.uid = uid;
		this.rid = rid;
		this.productCategoryId = productCategoryId;
	}

	@Id

	@Column(name = "URPCID", unique = true, nullable = false)
	public int getUrpcid() {
		return this.urpcid;
	}

	public void setUrpcid(int urpcid) {
		this.urpcid = urpcid;
	}

	@Column(name = "UID", nullable = false)
	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	@Column(name = "RID", nullable = false)
	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	@Column(name = "PRODUCT_CATEGORY_ID", nullable = false)
	public int getProductCategoryId() {
		return this.productCategoryId;
	}

	public void setProductCategoryId(int productCategoryId) {
		this.productCategoryId = productCategoryId;
	}

}
