package com.boc.model;
// Generated Nov 7, 2016 6:21:29 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LoanInterestRateVariance generated by hbm2java
 */
@Entity
@Table(name = "LOAN_INTEREST_RATE_VARIANCE", schema = "WFCONFIG")
public class LoanInterestRateVariance implements java.io.Serializable {

	private int lirvId;
	private ProductBase productBase;
	private BigDecimal varianceFixed;
	private BigDecimal varianceRateVariable1;
	private BigDecimal varianceRateVariable2;
	private int minRepaymentPeriod;
	private int maxRepaymentPeriod;

	public LoanInterestRateVariance() {
	}

	public LoanInterestRateVariance(int lirvId, ProductBase productBase, BigDecimal varianceFixed,
			BigDecimal varianceRateVariable1, BigDecimal varianceRateVariable2, int minRepaymentPeriod,
			int maxRepaymentPeriod) {
		this.lirvId = lirvId;
		this.productBase = productBase;
		this.varianceFixed = varianceFixed;
		this.varianceRateVariable1 = varianceRateVariable1;
		this.varianceRateVariable2 = varianceRateVariable2;
		this.minRepaymentPeriod = minRepaymentPeriod;
		this.maxRepaymentPeriod = maxRepaymentPeriod;
	}

	@Id

	@Column(name = "LIRV_ID", unique = true, nullable = false)
	public int getLirvId() {
		return this.lirvId;
	}

	public void setLirvId(int lirvId) {
		this.lirvId = lirvId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PID", nullable = false)
	public ProductBase getProductBase() {
		return this.productBase;
	}

	public void setProductBase(ProductBase productBase) {
		this.productBase = productBase;
	}

	@Column(name = "VARIANCE_FIXED", nullable = false, precision = 6, scale = 4)
	public BigDecimal getVarianceFixed() {
		return this.varianceFixed;
	}

	public void setVarianceFixed(BigDecimal varianceFixed) {
		this.varianceFixed = varianceFixed;
	}

	@Column(name = "VARIANCE_RATE_VARIABLE1", nullable = false, precision = 6, scale = 4)
	public BigDecimal getVarianceRateVariable1() {
		return this.varianceRateVariable1;
	}

	public void setVarianceRateVariable1(BigDecimal varianceRateVariable1) {
		this.varianceRateVariable1 = varianceRateVariable1;
	}

	@Column(name = "VARIANCE_RATE_VARIABLE2", nullable = false, precision = 6, scale = 4)
	public BigDecimal getVarianceRateVariable2() {
		return this.varianceRateVariable2;
	}

	public void setVarianceRateVariable2(BigDecimal varianceRateVariable2) {
		this.varianceRateVariable2 = varianceRateVariable2;
	}

	@Column(name = "MIN_REPAYMENT_PERIOD", nullable = false)
	public int getMinRepaymentPeriod() {
		return this.minRepaymentPeriod;
	}

	public void setMinRepaymentPeriod(int minRepaymentPeriod) {
		this.minRepaymentPeriod = minRepaymentPeriod;
	}

	@Column(name = "MAX_REPAYMENT_PERIOD", nullable = false)
	public int getMaxRepaymentPeriod() {
		return this.maxRepaymentPeriod;
	}

	public void setMaxRepaymentPeriod(int maxRepaymentPeriod) {
		this.maxRepaymentPeriod = maxRepaymentPeriod;
	}

}
