package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NationalityMaster generated by hbm2java
 */
@Entity
@Table(name = "NATIONALITY_MASTER", schema = "WFCONFIG")
public class NationalityMaster implements java.io.Serializable {

	private int id;
	private String citizencode;
	private String description;

	public NationalityMaster() {
	}

	public NationalityMaster(int id) {
		this.id = id;
	}

	public NationalityMaster(int id, String citizencode, String description) {
		this.id = id;
		this.citizencode = citizencode;
		this.description = description;
	}

	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "CITIZENCODE", length = 5)
	public String getCitizencode() {
		return this.citizencode;
	}

	public void setCitizencode(String citizencode) {
		this.citizencode = citizencode;
	}

	@Column(name = "DESCRIPTION", length = 25)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
