package com.boc.model;
// Generated Jun 28, 2016 2:29:44 PM by Hibernate Tools 4.0.0

import java.sql.Blob;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RequestMessageTransactions generated by hbm2java
 */
@Entity
@Table(name = "REQUEST_MESSAGE_TRANSACTIONS", schema = "WFCONFIG")
public class RequestMessageTransactions implements java.io.Serializable {

	private int transactionId;
	private String wfRefNo;
	private String wobNo;
	private String branchCode;
	private String productCode;
	private Blob requestXml;
	private String responseActivityName;
	private String mapName;
	private String serviceStatusCode;
	private String serviceStatusDesc;
	private String messageStatusCode;
	private String messageStatusDesc;
	private String retry;
	private String className;

	public RequestMessageTransactions() {
	}

	public RequestMessageTransactions(int transactionId, String wfRefNo) {
		this.transactionId = transactionId;
		this.wfRefNo = wfRefNo;
	}

	public RequestMessageTransactions(int transactionId, String wfRefNo, String wobNo, String branchCode,
			String productCode, Blob requestXml, String responseActivityName, String mapName, String serviceStatusCode,
			String serviceStatusDesc, String messageStatusCode, String messageStatusDesc, String retry,
			String className) {
		this.transactionId = transactionId;
		this.wfRefNo = wfRefNo;
		this.wobNo = wobNo;
		this.branchCode = branchCode;
		this.productCode = productCode;
		this.requestXml = requestXml;
		this.responseActivityName = responseActivityName;
		this.mapName = mapName;
		this.serviceStatusCode = serviceStatusCode;
		this.serviceStatusDesc = serviceStatusDesc;
		this.messageStatusCode = messageStatusCode;
		this.messageStatusDesc = messageStatusDesc;
		this.retry = retry;
		this.className = className;
	}

	@Id

	@Column(name = "TRANSACTION_ID", unique = true, nullable = false)
	public int getTransactionId() {
		return this.transactionId;
	}

	public void setTransactionId(int transactionId) {
		this.transactionId = transactionId;
	}

	@Column(name = "WF_REF_NO", nullable = false, length = 20)
	public String getWfRefNo() {
		return this.wfRefNo;
	}

	public void setWfRefNo(String wfRefNo) {
		this.wfRefNo = wfRefNo;
	}

	@Column(name = "WOB_NO", length = 50)
	public String getWobNo() {
		return this.wobNo;
	}

	public void setWobNo(String wobNo) {
		this.wobNo = wobNo;
	}

	@Column(name = "BRANCH_CODE", length = 5)
	public String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(String branchCode) {
		this.branchCode = branchCode;
	}

	@Column(name = "PRODUCT_CODE", length = 5)
	public String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(String productCode) {
		this.productCode = productCode;
	}

	@Column(name = "REQUEST_XML")
	public Blob getRequestXml() {
		return this.requestXml;
	}

	public void setRequestXml(Blob requestXml) {
		this.requestXml = requestXml;
	}

	@Column(name = "RESPONSE_ACTIVITY_NAME", length = 100)
	public String getResponseActivityName() {
		return this.responseActivityName;
	}

	public void setResponseActivityName(String responseActivityName) {
		this.responseActivityName = responseActivityName;
	}

	@Column(name = "MAP_NAME", length = 25)
	public String getMapName() {
		return this.mapName;
	}

	public void setMapName(String mapName) {
		this.mapName = mapName;
	}

	@Column(name = "SERVICE_STATUS_CODE", length = 3)
	public String getServiceStatusCode() {
		return this.serviceStatusCode;
	}

	public void setServiceStatusCode(String serviceStatusCode) {
		this.serviceStatusCode = serviceStatusCode;
	}

	@Column(name = "SERVICE_STATUS_DESC", length = 100)
	public String getServiceStatusDesc() {
		return this.serviceStatusDesc;
	}

	public void setServiceStatusDesc(String serviceStatusDesc) {
		this.serviceStatusDesc = serviceStatusDesc;
	}

	@Column(name = "MESSAGE_STATUS_CODE", length = 3)
	public String getMessageStatusCode() {
		return this.messageStatusCode;
	}

	public void setMessageStatusCode(String messageStatusCode) {
		this.messageStatusCode = messageStatusCode;
	}

	@Column(name = "MESSAGE_STATUS_DESC", length = 50)
	public String getMessageStatusDesc() {
		return this.messageStatusDesc;
	}

	public void setMessageStatusDesc(String messageStatusDesc) {
		this.messageStatusDesc = messageStatusDesc;
	}

	@Column(name = "RETRY", length = 100)
	public String getRetry() {
		return this.retry;
	}

	public void setRetry(String retry) {
		this.retry = retry;
	}

	@Column(name = "CLASS_NAME", length = 100)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

}
