package com.boc.model;
// Generated Jun 10, 2016 11:13:38 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RoleBase generated by hbm2java
 */
@Entity
@Table(name = "ROLE_BASE", schema = "WFCONFIG", uniqueConstraints = @UniqueConstraint(columnNames = "ROLE_NAME"))
public class RoleBase implements java.io.Serializable {

	private int rid;
	private String roleName;
	private String roleLabel;
	private String roleDescription;

	public RoleBase() {
	}

	public RoleBase(int rid, String roleName, String roleLabel) {
		this.rid = rid;
		this.roleName = roleName;
		this.roleLabel = roleLabel;
	}

	public RoleBase(int rid, String roleName, String roleLabel, String roleDescription) {
		this.rid = rid;
		this.roleName = roleName;
		this.roleLabel = roleLabel;
		this.roleDescription = roleDescription;
	}

	@Id

	@Column(name = "RID", unique = true, nullable = false)
	public int getRid() {
		return this.rid;
	}

	public void setRid(int rid) {
		this.rid = rid;
	}

	@Column(name = "ROLE_NAME", unique = true, nullable = false, length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "ROLE_LABEL", nullable = false, length = 50)
	public String getRoleLabel() {
		return this.roleLabel;
	}

	public void setRoleLabel(String roleLabel) {
		this.roleLabel = roleLabel;
	}

	@Column(name = "ROLE_DESCRIPTION", length = 50)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

}
