package com.boc.model;
// Generated Jul 21, 2016 2:52:03 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CollateralBase generated by hbm2java
 */
@Entity
@Table(name = "COLLATERAL_BASE", schema = "WFCONFIG")
public class CollateralBase implements java.io.Serializable {

	private int cid;
	private String collateralCode;
	private String collateralDescription;

	public CollateralBase() {
	}

	public CollateralBase(int cid, String collateralCode, String collateralDescription) {
		this.cid = cid;
		this.collateralCode = collateralCode;
		this.collateralDescription = collateralDescription;
	}

	@Id

	@Column(name = "CID", unique = true, nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "COLLATERAL_CODE", nullable = false, length = 10)
	public String getCollateralCode() {
		return this.collateralCode;
	}

	public void setCollateralCode(String collateralCode) {
		this.collateralCode = collateralCode;
	}

	@Column(name = "COLLATERAL_DESCRIPTION", nullable = false, length = 500)
	public String getCollateralDescription() {
		return this.collateralDescription;
	}

	public void setCollateralDescription(String collateralDescription) {
		this.collateralDescription = collateralDescription;
	}

}
