package com.boc.model;
// Generated Jul 29, 2016 11:14:54 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRoleProductCategoryRlcMapping generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE_PRODUCT_CATEGORY_RLC_MAPPING", schema = "WFCONFIG")
public class UserRoleProductCategoryRlcMapping implements java.io.Serializable {

	private int urpcrlcid;
	private int urpcid;
	private int rlcId;

	public UserRoleProductCategoryRlcMapping() {
	}

	public UserRoleProductCategoryRlcMapping(int urpcrlcid, int urpcid, int rlcId) {
		this.urpcrlcid = urpcrlcid;
		this.urpcid = urpcid;
		this.rlcId = rlcId;
	}

	@Id

	@Column(name = "URPCRLCID", unique = true, nullable = false)
	public int getUrpcrlcid() {
		return this.urpcrlcid;
	}

	public void setUrpcrlcid(int urpcrlcid) {
		this.urpcrlcid = urpcrlcid;
	}

	@Column(name = "URPCID", nullable = false)
	public int getUrpcid() {
		return this.urpcid;
	}

	public void setUrpcid(int urpcid) {
		this.urpcid = urpcid;
	}

	@Column(name = "RLC_ID", nullable = false)
	public int getRlcId() {
		return this.rlcId;
	}

	public void setRlcId(int rlcId) {
		this.rlcId = rlcId;
	}

}
